def generate_markdown(sector, analysis):

    report = f"""
        # {sector.title()} Sector Trade Opportunities (India)

        {analysis}

        ---

        Generated by Trade Opportunities API
        """

    return report